name: Fix code style

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.php-cs-fixer.dist.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Fix code style
        run: composer fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Apply CS fixes
