name: Run tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test on PHP${{matrix.php}}

    strategy:
     matrix:
        php: ["8.1", "8.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run tests
        run: composer test
