name: Run tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  php-test:
    runs-on: ubuntu-latest

    name: Test on PHP${{matrix.php}}

    strategy:
     matrix:
        php: ["8.1", "8.2", "8.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run tests
        run: composer test

  postgis-test:
    runs-on: ubuntu-latest

    name: Test with PostGIS

    services:
      postgis:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_DB: sfa
          POSTGRES_USER: sfa
          POSTGRES_PASSWORD: sfa
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run tests
        run: composer test-pg
